spring:
  application:
    name: chakchak

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    log-topic: ${KAFKA_LOG_TOPIC}

    # Producer 설정 (String key, JSON value)
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false  # 수신 측 타입 헤더 미포함(호환성)

  apick:
    base_url: ${APICK_BASE_URL}
    auth_key: ${APICK_AUTH_KEY}

  openai:
    api:
      key: ${OPENAI_API_KEY}
      url: ${OPENAI_API_URL}
      model: ${OPENAI_API_MODEL}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: client_secret_post # POST
            client-name: kakao
            redirect-uri: ${REDIRECT_URL}
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    ssl:
      enabled: ${SSL_ENABLED}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-seconds: 1800 # 1800초 = 30분
  refresh-token-validity-seconds: 259200 # 259200초 = 3일

auth:
  cookie:
    domain: ${AUTH_COOKIE_DOMAIN}
    secure: ${AUTH_COOKIE_SECURE}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha


cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ${REGION}

kakao:
  admin-key: ${ADMIN}

juso:
  base-url: ${JUSO_ADMCD_BASE_URL}
  api-key: ${JUSO_ADMCD_API_KEY}

base:
  url: https://localhost:5173 #${BASE_URL}
